#!/usr/bin/env python3
"""results/*.json -> tables/*.tex.  Never hand-type a number into the paper."""
import glob, json, os

os.makedirs("tables", exist_ok=True)
rows = []
for p in sorted(glob.glob("results/*.json")):
    with open(p) as fh:
        rows.append((os.path.basename(p)[:-5], json.load(fh)))

if not rows:
    raise SystemExit("no results/*.json yet — run an experiment first")

metrics = [k for k in rows[0][1] if isinstance(rows[0][1][k], (int, float))]
with open("tables/main.tex", "w") as fh:
    fh.write("% GENERATED by scripts/make_tables.py — do not edit\n")
    fh.write("\\begin{tabular}{l" + "c" * len(metrics) + "}\n\\toprule\n")
    fh.write("Run & " + " & ".join(m.replace("_", " ") for m in metrics) + " \\\\\n\\midrule\n")
    for name, d in rows:
        fh.write(name.replace("_", " ") + " & "
                 + " & ".join(f"{d.get(m, float('nan')):.2f}" for m in metrics)
                 + " \\\\\n")
    fh.write("\\bottomrule\n\\end{tabular}\n")
print("wrote tables/main.tex")
